<div class="feature-list">
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
  <div class="feature-item">A venir sous peu</div>
</div>